import os
import numpy
import arcpy
import pandas
from getintervals import getintervals
from makerasters import makerasters
from islandmode import islandmode
from calcmatrices import calcmatrices
os.chdir(os.path.dirname(os.path.abspath(__file__)))
path = os.getcwd()
inputpath = "input/"
outpath = "output/"

#read sea level file (from Bintanja et al, 2008)
sealvl = pandas.read_csv(inputpath+'sealvl.csv')
#print(sealvl)

#input checking subroutine for time value
while True:
    try:
        #Prompt user for time cutoff input value
        time = float(raw_input("Please enter a cutoff time (kya) [0.1 to 3000, in intervals of 0.1] "))
        if 0.1 <= time <= 3000:
            break #break out of while loop if input is within accepted time range
        else:
            raise ValueError #raise exception if input is not valid
    except ValueError:
        print("Please enter a valid cutoff time") #prompt user to re-enter input, loop back to start of input checking

#input checking subroutine for interval value
while True:
    try:
        #prompt user for number of intervals
        intervals = int(raw_input("Enter the number of intervals [integer, from 1 to " + str(int(time*10))+"]: "))
        if 1 <= intervals <= (time*10): #check to see if interval value is within valid range
            break #if valid, break out of checking subroutine
        else:
            raise ValueError
    except ValueError:
        print("Please enter a valid interval value")

while True:
    try:
        #prompt user for input bathymetry raster
        inputraster = raw_input("Please enter the file name of the input bathymetry raster (in .asc format) ")
        if (inputraster in os.listdir(inputpath)) & (inputraster.endswith(".asc")): #check list of files with .asc extension in input folder
            break #if user input matches file in input folder, break out of input checking subroutine
        else:
            raise ValueError
    except ValueError:
        print("Please enter a valid .asc file")

# while True:
#     try:
#         #prompt user to select analysis mode
#         mode = int(raw_input("Choose analysis mode [1: Individual mode, 0: Island mode] "))
#         if mode in [0,1]:
#             break
#         else:
#             raise ValueError
#     except ValueError:
#         print("Please enter a valid number (0 or 1) to choose the analysis mode ")

while True:
    try:
        #prompt user for point shapefile input
        points = raw_input("Enter the filename of the shapefile containing input source points ")
        if (points in os.listdir(inputpath)) & (points.endswith(".shp")):
            break
        else:
            raise ValueError
    except ValueError:
        print("Please enter a valid .shp file ")
        
while True:
    try:
        #prompt user for project projection
        epsg = int(raw_input("Enter the EPSG spatial reference value for your target area [integer between 1024 and 32767] "))
        if ((epsg >= 1024) & (epsg <= 32767)):
            break
        else:
            raise ValueError
    except ValueError:
        print("Please enter a valid EPSG reference value ")

#define spatial reference presets
spatialref_default = arcpy.SpatialReference(4326)
spatialref_proj = arcpy.SpatialReference(epsg)
spatial_ref = arcpy.Describe(inputpath+points)
#check projection of point shapefile and set projection if unknown
if spatial_ref.name == "Unknown":
    print("The source points file has an unknown spatial reference, setting to default projection (EPSG 4326) ")
    arcpy.DefineProjection_management(points, spatialref_default)

#reproject shapefile to correct projection
points_projected = "sourcepoints_projected.shp"
arcpy.Project_management(inputpath+points,inputpath+points_projected,spatialref_proj)

#calculate interval values and time interval counts
getintervals(sealvl,time,intervals)
#import interval file generated by getintervals subroutine
intervalfile = pandas.read_csv(outpath+'intervals.csv')
#run subroutine to generate sea level rasters for each interval
makerasters(intervalfile,inputraster,epsg)
#run subroutine to generate distance matrices for each sea level interval
islandmode(intervalfile,points_projected)
#run subroutine to calculate time-weighted average across distance matrices
calcmatrices(outpath,intervalfile)
